### ISSUE TITLE
You've been busy!

### ISSUE THREAD

**Issue by ghenry** [cloudwebrtc/go-sip-ua#13]
Nice! Was just looking for something like this to create a SIP honeypot.

**Comment by cloudwebrtc** [comment]
I want to use this go library to write a modern IP phone switching system, using golang/pion/webrtc/flutter these modern programming languages and protocol stacks, so that the development of voip systems is no longer painful, and it is more suitable for high-concurrency cloud deployment. Better integration of webrtc technology,

Not only the telephone system, but it is also very easy to interface with the old video conference system. We only need a small amount of c/c++ native code to process a/v codec.

**Comment by ghenry** [comment]
Have you seen routr?

There are a lot of great server side projects to review. Depends on your
scope :)
